/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.junit)
    implementation(libs.com.ceridwen.util)
    implementation(libs.org.apache.commons.commons.lang3)
    implementation(libs.commons.net)
    implementation(libs.commons.logging)
    implementation(libs.commons.beanutils)
    implementation(libs.io.netty.transport)
    implementation(libs.io.netty.handler)
    implementation(libs.org.bouncycastle.bcpkix.jdk18on)
}

group = "com.xingzhi.circulation"
version = "2.11.2"
description = "Ceridwen's SIP Circulation Library for Java"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc> {
    options.encoding = "UTF-8"
}
